# Generated by Django 3.0.3 on 2020-03-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netease_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('pic', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_year', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netease_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netease_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Artist')),
            ],
        ),
    ]
