# Generated by Django 3.0.3 on 2020-03-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20200302_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='publish_year',
            new_name='publish_time',
        ),
    ]
