# Generated by Django 3.0.3 on 2020-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_auto_20200302_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ext',
            field=models.CharField(choices=[('m4a', 'm4a'), ('mp3', 'mp3'), ('ape', 'ape'), ('flac', 'flac')], default='m4a', max_length=16),
        ),
    ]
