# Generated by Django 3.0.3 on 2020-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0005_song_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.CharField(blank=True, choices=[('netease', '网易云音乐'), ('qq', 'qq音乐'), ('kugou', '酷狗音乐')], max_length=16, null=True),
        ),
    ]
