# Generated by Django 3.0.3 on 2020-03-25 23:18
import core.models
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_auto_20200326_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
