# Generated by Django 3.0.3 on 2020-10-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('netease_id', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(choices=[('0', 'Unknown'), ('1', 'male'), ('2', 'female')], max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.User')),
            ],
        ),
    ]
