# Generated by Django 3.0.3 on 2020-10-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0011_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='netease_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='netease_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='netease_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='netease_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
