# Generated by Django 3.0.3 on 2020-10-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0012_auto_20201023_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='netease_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
