# Generated by Django 3.0.3 on 2020-10-22 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_comment_netease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Song'),
            preserve_default=False,
        ),
    ]
