# Generated by Django 3.0.3 on 2020-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_comment_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied',
            field=models.ManyToManyField(blank=True, null=True, related_name='_comment_replied_+', to='meta.Comment'),
        ),
    ]
