# Generated by Django 3.0.3 on 2020-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0016_auto_20201028_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='netease_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='netease_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
