# Generated by Django 3.0.3 on 2020-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
