# Generated by Django 3.0.3 on 2020-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawler',
            name='song',
        ),
        migrations.AddField(
            model_name='crawler',
            name='netease_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
