# Generated by Django 3.0.3 on 2020-10-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20201028_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='cursor',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
