# Generated by Django 3.0.3 on 2020-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_crawler_cursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='cursor',
            field=models.BigIntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='crawler',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
