# Generated by Django 3.0.3 on 2020-11-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_analyzecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('processed', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
    ]
