# Generated by Django 3.0.3 on 2020-11-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzecomment',
            name='word_en',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
